M48
; DRILL file {KiCad (6.0.0-rc1-323-gb9e66d8b98)} date Thu Dec  9 23:13:02 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-09T23:13:02+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-323-gb9e66d8b98)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.4962Y0.2026
X0.7238Y0.2026
T0
M30
